"""initial_hexagonal_schema

Revision ID: f6171ece1321
Revises: 
Create Date: 2026-06-04 14:51:32.409200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6171ece1321'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('club_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('club_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('club_id', sa.String(), nullable=False),
    sa.Column('active_modules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('button_layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id')
    )
    op.create_table('club_memberships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('club_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'club_id')
    )
    op.create_table('club_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('club_id', sa.String(), nullable=False),
    sa.Column('active_match', sa.String(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('editor_pin', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id')
    )
    op.create_table('players',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('club_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('club_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('club_id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('opponent', sa.String(), nullable=False),
    sa.Column('place', sa.String(), nullable=False),
    sa.Column('age_category', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('season_id', sa.String(), nullable=True),
    sa.Column('q1_my', sa.Integer(), nullable=False),
    sa.Column('q1_opp', sa.Integer(), nullable=False),
    sa.Column('q2_my', sa.Integer(), nullable=False),
    sa.Column('q2_opp', sa.Integer(), nullable=False),
    sa.Column('q3_my', sa.Integer(), nullable=False),
    sa.Column('q3_opp', sa.Integer(), nullable=False),
    sa.Column('q4_my', sa.Integer(), nullable=False),
    sa.Column('q4_opp', sa.Integer(), nullable=False),
    sa.Column('final_my', sa.Integer(), nullable=False),
    sa.Column('final_opp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_table('player_age_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('age_category', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'age_category')
    )
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('club_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('subtype', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('video_timestamp', sa.Integer(), nullable=True),
    sa.Column('is_goal_from_play_positional', sa.Integer(), nullable=False),
    sa.Column('is_goal_from_play_counter', sa.Integer(), nullable=False),
    sa.Column('is_goal_from_center_positional', sa.Integer(), nullable=False),
    sa.Column('is_assist_positional', sa.Integer(), nullable=False),
    sa.Column('is_shot_saved_gk_positional', sa.Integer(), nullable=False),
    sa.Column('is_shot_miss_turnover_positional', sa.Integer(), nullable=False),
    sa.Column('is_shot_miss_reset30_positional', sa.Integer(), nullable=False),
    sa.Column('is_bad_pass_turnover_positional', sa.Integer(), nullable=False),
    sa.Column('is_bad_pass_no_turnover_positional', sa.Integer(), nullable=False),
    sa.Column('is_turnover_1v1_positional', sa.Integer(), nullable=False),
    sa.Column('is_shot_clock_violation_positional', sa.Integer(), nullable=False),
    sa.Column('is_excl_drawn_field_positional', sa.Integer(), nullable=False),
    sa.Column('is_excl_drawn_center_positional', sa.Integer(), nullable=False),
    sa.Column('is_penalty_drawn_field_positional', sa.Integer(), nullable=False),
    sa.Column('is_penalty_drawn_center_positional', sa.Integer(), nullable=False),
    sa.Column('is_goal_from_center_man_up', sa.Integer(), nullable=False),
    sa.Column('is_goal_5m_man_up', sa.Integer(), nullable=False),
    sa.Column('is_assist_man_up', sa.Integer(), nullable=False),
    sa.Column('is_shot_saved_gk_man_up', sa.Integer(), nullable=False),
    sa.Column('is_shot_miss_turnover_man_up', sa.Integer(), nullable=False),
    sa.Column('is_shot_miss_reset30_man_up', sa.Integer(), nullable=False),
    sa.Column('is_bad_pass_turnover_man_up', sa.Integer(), nullable=False),
    sa.Column('is_bad_pass_no_turnover_man_up', sa.Integer(), nullable=False),
    sa.Column('is_turnover_1v1_man_up', sa.Integer(), nullable=False),
    sa.Column('is_shot_clock_violation_man_up', sa.Integer(), nullable=False),
    sa.Column('is_goal_5m_penalty', sa.Integer(), nullable=False),
    sa.Column('is_no_return_positional', sa.Integer(), nullable=False),
    sa.Column('is_excl_committed_field_positional', sa.Integer(), nullable=False),
    sa.Column('is_excl_committed_center_positional', sa.Integer(), nullable=False),
    sa.Column('is_penalty_committed_field_positional', sa.Integer(), nullable=False),
    sa.Column('is_penalty_committed_center_positional', sa.Integer(), nullable=False),
    sa.Column('is_shot_saved_gk_def_positional', sa.Integer(), nullable=False),
    sa.Column('is_steal_positional', sa.Integer(), nullable=False),
    sa.Column('is_block_hand_positional', sa.Integer(), nullable=False),
    sa.Column('is_no_block_positional', sa.Integer(), nullable=False),
    sa.Column('is_no_return_man_up', sa.Integer(), nullable=False),
    sa.Column('is_excl_committed_field_man_up', sa.Integer(), nullable=False),
    sa.Column('is_excl_committed_center_man_up', sa.Integer(), nullable=False),
    sa.Column('is_penalty_committed_field_man_up', sa.Integer(), nullable=False),
    sa.Column('is_penalty_committed_center_man_up', sa.Integer(), nullable=False),
    sa.Column('is_shot_saved_gk_def_man_up', sa.Integer(), nullable=False),
    sa.Column('is_steal_man_up', sa.Integer(), nullable=False),
    sa.Column('is_block_hand_man_up', sa.Integer(), nullable=False),
    sa.Column('is_no_block_man_up', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_roster',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('club_id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id')
    )
    op.create_table('youtube_streams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('youtube_url', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('stream_start_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube_streams')
    op.drop_table('match_roster')
    op.drop_table('events')
    op.drop_table('player_age_categories')
    op.drop_table('matches')
    op.drop_table('seasons')
    op.drop_table('players')
    op.drop_table('club_settings')
    op.drop_table('club_memberships')
    op.drop_table('club_configs')
    op.drop_table('users')
    op.drop_table('clubs')
    # ### end Alembic commands ###
